In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [2]:
dataset=datasets.load_iris()
x=dataset.data
y=dataset.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=71)
model=GaussianNB()
model.fit(x_train,y_train)
predicted=model.predict(x_test)
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.89      0.94      0.92        18
           2       0.92      0.85      0.88        13

    accuracy                           0.93        45
   macro avg       0.94      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

[[14  0  0]
 [ 0 17  1]
 [ 0  2 11]]
