In [1]:
from sklearn.datasets import load_boston
boston=load_boston()
#print(boston.DESCR)
print(boston.data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDRegressor
x_train,x_test,y_train,y_test=train_test_split(boston.data,boston.target)



In [3]:
from sklearn.preprocessing import StandardScaler
xscaled=StandardScaler()
yscaled=StandardScaler()
print(y_train.shape)
y_train=y_train.reshape(y_train.shape[0],1)
print(y_train.shape)
###similarly change testing data
y_test=y_test.reshape(y_test.shape[0],1)
print(y_test.shape)

(379,)
(379, 1)
(127, 1)


In [9]:
x_train=xscaled.fit_transform(x_train)
y_train=yscaled.fit_transform(y_train)
x_test=xscaled.transform(x_test)
y_test=yscaled.transform(y_test)

In [11]:
import numpy as np
from sklearn.model_selection import cross_val_score
regressor=SGDRegressor(loss='squared_loss')
scores=cross_val_score(regressor,x_train,y_train,cv=5)
print('Cross validation scores :',scores)
print('Avg. Cross validation scores :',np.mean(scores))
regressor.fit(x_train,y_train)
print("Test set r-squared score",regressor.score(x_test,y_test))

Cross validation scores : [0.50532822 0.7717374  0.69903754 0.7126471  0.73062605]
Avg. Cross validation scores : 0.6838752609381652
Test set r-squared score 0.7435043003771409


C:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwar

In [12]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
scores=cross_val_score(regressor,x_train,y_train,cv=5)
print('Cross validation scores :',scores)
print('Avg. Cross validation scores :',np.mean(scores))
regressor.fit(x_train,y_train)
print("Test set r-squared score",regressor.score(x_test,y_test))

Cross validation scores : [0.52134735 0.77312356 0.66056392 0.73074989 0.75051516]
Avg. Cross validation scores : 0.6872599759598408
Test set r-squared score 0.7468003908648416
