In [1]:
import pandas as pd
from sklearn import preprocessing
data=[[-1,2],[-0.5,6],[0,10],[1,18]]
scalar=preprocessing.StandardScaler()
scaled_values=pd.DataFrame(scalar.fit_transform(data),columns=['col1','col2'])
print(pd.DataFrame(data))
print(scaled_values)

     0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18
       col1      col2
0 -1.183216 -1.183216
1 -0.507093 -0.507093
2  0.169031  0.169031
3  1.521278  1.521278


In [2]:
import pandas as pd
from sklearn import preprocessing
data=[[-1,2],[-0.5,6],[0,10],[1,18]]
scaled_values=pd.DataFrame(preprocessing.scale(data),columns=['col1','col2'])
print(pd.DataFrame(data))
print(scaled_values)

     0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18
       col1      col2
0 -1.183216 -1.183216
1 -0.507093 -0.507093
2  0.169031  0.169031
3  1.521278  1.521278


In [4]:
from sklearn import preprocessing
import numpy as np
X=np.array([[5,7,0,9,2],
          [6,8,12,3,5],
          [0,4,6,13,16]
           ])
print(preprocessing.scale(X))

[[ 0.50800051  0.39223227 -1.22474487  0.16222142 -0.94154292]
 [ 0.88900089  0.98058068  1.22474487 -1.29777137 -0.44307902]
 [-1.3970014  -1.37281295  0.          1.13554995  1.38462194]]
