In [1]:
from numpy import diag,array,dot
from scipy.linalg import svd
A=array([[1,2],[3,4],[5,6]])
print(A)
U,S,VT=svd(A)
print('matrix A: \n', A)
print('matrix U: \n', U)
print('matrix S: \n', S)
print('matrix VT: \n', VT)
print(U.shape)
print(A.shape)
print(S.shape)

[[1 2]
 [3 4]
 [5 6]]
matrix A: 
 [[1 2]
 [3 4]
 [5 6]]
matrix U: 
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
matrix S: 
 [9.52551809 0.51430058]
matrix VT: 
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
(3, 3)
(3, 2)
(2,)


In [8]:
import numpy as np
Sigma=np.zeros((A.shape[0],A.shape[1]))
print(Sigma)
print(diag(S))
Sigma[:A.shape[1],:A.shape[1]]=diag(S)
print(Sigma)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[9.52551809 0.        ]
 [0.         0.51430058]]
[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]


In [3]:
print(S)
print(A.shape[1])

[9.52551809 0.51430058]
2


In [11]:
A_mod=U.dot(Sigma.dot(VT))
print(A_mod)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
